version: 2
jobs:
  build:
    working_directory: /usr/src
    docker:
      - image: determinant/inference
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run: 
          name: Install Aboleth, along with all Python dev dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[dev]
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run: 
          command: |
            . venv/bin/activate
            pip freeze
            pip3 freeze
            pytest . --cov=./