version: 2
jobs:
  build:
    working_directory: /usr/src
    docker:
      - image: determinant/inference
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
      - run: 
          name: Installing Aboleth and all other Python dev dependencies
          command: |
            python3 -m venv --system-site-packages /opt/envs/venv 
            . /opt/envs/venv/bin/activate
            pip3 install -e .[dev]
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run: 
          name: Running tests
          command: |
            . /opt/envs/venv/bin/activate
            pytest . --cov=./ --cov-report=html:test-reports/coverage
      - store_artifacts:
          path: test-reports/coverage
          destination: coverage-report